#!/usr/bin/env python3
"""
Rating-sheet builder for the ReflectAI human evaluation
=======================================================
Produces everything you need for the two human-rated dimensions:

  Likert quality       -> Section VII-C, Fig. 6
  Acquaintance test    -> Section VII-C, the AcqDetectRate / StrangerDetectRate
                          numbers, following Guo et al. [14]

WHAT IT MAKES
-------------
  rating_sheet.csv    give this to raters; twin and real answers are shuffled
                      and unlabelled
  answer_key.csv      KEEP THIS PRIVATE. Maps each item back to twin/real.
  INSTRUCTIONS.txt    hand to raters verbatim

WORKFLOW
--------
  1. python make_rating_sheets.py --profile-id <id>
  2. Send rating_sheet.csv + INSTRUCTIONS.txt to each rater.
     Rater fills the four empty columns and sends it back.
  3. python make_rating_sheets.py --score sheets/*.csv
     -> writes likert_ratings.csv and discrimination.csv
  4. Re-run eval_harness.py to fold them into data.tex.

WHY IT IS BLINDED
-----------------
If a rater can tell which answers came from the machine, the detection rate
measures nothing. Shuffling and stripping labels is the whole experiment.
"""

import argparse
import csv
import glob
import json
import os
import random
import sys
from pathlib import Path

BACKEND_PATH = os.environ.get(
    "REFLECTAI_BACKEND", os.path.expanduser(r"~\Reflect-AI\backend"))
sys.path.insert(0, BACKEND_PATH)

try:
    from dotenv import load_dotenv
    _e = os.path.join(BACKEND_PATH, ".env")
    if os.path.exists(_e):
        load_dotenv(_e)
except ImportError:
    pass


def build(profile_id, n_items, seed):
    from app.services.twin_engine import DigitalTwinEngine
    from app.adapters import ollama_adapter
    sys.path.insert(0, str(Path(__file__).parent))
    from eval_harness import ollama_chat, PROBES

    engine = DigitalTwinEngine()
    ctx = engine.build_twin_context(profile_id, force_reload=True)
    seed_msgs = ollama_adapter.build_messages(ctx)

    # The person's own words, straight from the stored interview.
    source = engine.load_source_conversation(profile_id)
    real = [m["content"].strip() for m in source
            if m.get("role") == "user" and len(m.get("content", "").strip()) > 25]

    if len(real) < 3:
        sys.exit("Too few usable interview answers to build a fair test.")

    items = []
    for i in range(n_items):
        probe = PROBES[i % len(PROBES)]
        twin, _, _ = ollama_chat(seed_msgs + [{"role": "user",
                                               "content": probe}])
        items.append({"prompt": probe, "text": twin.strip(), "origin": "twin"})

    for i, answer in enumerate(real[:n_items]):
        items.append({"prompt": "(from the original interview)",
                      "text": answer, "origin": "real"})

    rng = random.Random(seed)
    rng.shuffle(items)

    with open("rating_sheet.csv", "w", newline="", encoding="utf8") as f:
        w = csv.writer(f)
        w.writerow(["item_id", "prompt", "response",
                    "relevance_1to5", "coherence_1to5",
                    "personalisation_1to5", "guess_twin_or_real"])
        for n, it in enumerate(items, 1):
            w.writerow([f"I{n:03d}", it["prompt"], it["text"], "", "", "", ""])

    with open("answer_key.csv", "w", newline="", encoding="utf8") as f:
        w = csv.writer(f)
        w.writerow(["item_id", "origin"])
        for n, it in enumerate(items, 1):
            w.writerow([f"I{n:03d}", it["origin"]])

    Path("INSTRUCTIONS.txt").write_text(f"""\
ReflectAI evaluation - rater instructions
=========================================

You have a spreadsheet of {len(items)} short conversational responses.
Some were written by a real person. Some were generated by an AI system
trained on a ten-minute interview with that person. They are mixed
together in random order and we will not tell you which is which.

For EACH row, fill in four columns:

  relevance_1to5         Does the response actually answer the prompt?
                         1 = ignores it entirely, 5 = answers it directly

  coherence_1to5         Does it read as clear, sensible writing?
                         1 = confusing or contradictory, 5 = perfectly clear

  personalisation_1to5   Does it sound like a specific individual rather
                         than a generic assistant?
                         1 = could be any chatbot, 5 = distinctly someone

  guess_twin_or_real     Type exactly: twin   or   real
                         Guess even when unsure. Do not leave blank.

Please do not discuss items with other raters until everyone is finished,
and do not skip rows. If you know the person the system was built from,
say so when you return the sheet - that is useful, not disqualifying.

Rename the file to include your name, e.g. rating_sheet_priya.csv, and put
it in a folder called sheets/ when you return it.

Thank you.
""", encoding="utf8")

    print(f"rating_sheet.csv    {len(items)} items "
          f"({n_items} twin, {min(n_items, len(real))} real)")
    print("answer_key.csv      KEEP PRIVATE")
    print("INSTRUCTIONS.txt    send to raters")


def score(paths):
    key = {}
    if not Path("answer_key.csv").exists():
        sys.exit("answer_key.csv not found - run the build step first.")
    with open("answer_key.csv", encoding="utf8") as f:
        for row in csv.DictReader(f):
            key[row["item_id"]] = row["origin"]

    likert, discrim = [], []
    for path in paths:
        rater = Path(path).stem.replace("rating_sheet_", "") or "R"
        acquainted = "acq" in rater.lower()
        with open(path, encoding="utf8") as f:
            for row in csv.DictReader(f):
                iid = row.get("item_id", "").strip()
                if key.get(iid) != "twin":
                    pass  # ratings on real answers are the control, kept below
                for dim, col in (("Relevance", "relevance_1to5"),
                                 ("Coherence", "coherence_1to5"),
                                 ("Personalisation", "personalisation_1to5")):
                    v = (row.get(col) or "").strip()
                    if v.isdigit() and key.get(iid) == "twin":
                        likert.append({"dimension": dim, "rating": int(v),
                                       "rater_id": rater, "turn_id": iid,
                                       "notes": ""})
                g = (row.get("guess_twin_or_real") or "").strip().lower()
                if g in ("twin", "real") and iid in key:
                    discrim.append({
                        "rater_type": "acquaintance" if acquainted else "stranger",
                        "correct": int(g == key[iid]),
                        "rater_id": rater, "turn_id": iid, "notes": ""})

    with open("likert_ratings.csv", "w", newline="", encoding="utf8") as f:
        w = csv.DictWriter(f, ["dimension", "rating", "rater_id",
                               "turn_id", "notes"])
        w.writeheader()
        w.writerows(likert)
    with open("discrimination.csv", "w", newline="", encoding="utf8") as f:
        w = csv.DictWriter(f, ["rater_type", "correct", "rater_id",
                               "turn_id", "notes"])
        w.writeheader()
        w.writerows(discrim)

    acc = sum(d["correct"] for d in discrim)
    print(f"likert_ratings.csv   {len(likert)} ratings")
    print(f"discrimination.csv   {len(discrim)} judgements, "
          f"{100*acc/len(discrim):.0f}% correct overall" if discrim else "")
    print("\nNow re-run: python eval_harness.py --profile-id <id>")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile-id")
    ap.add_argument("--items", type=int, default=12,
                    help="twin responses to generate (default 12)")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--score", nargs="*",
                    help="score returned sheets, e.g. --score sheets/*.csv")
    a = ap.parse_args()

    if a.score is not None:
        paths = []
        for p in (a.score or ["sheets/*.csv"]):
            paths.extend(glob.glob(p))
        if not paths:
            sys.exit("No sheets found.")
        score(paths)
    elif a.profile_id:
        build(a.profile_id, a.items, a.seed)
    else:
        ap.error("give --profile-id to build, or --score to score")
