"""
VoiceChatService — the Vapi-backed voice chat channel.

Mirrors TextChatService's shape (same DigitalTwinEngine underneath, same
shared conversation memory) but adds what a real-time voice call needs
that a text turn doesn't: a Vapi assistant config for the browser SDK,
call lifecycle tracking, and webhook handling.

VAPI_LLM_PROVIDER picks which adapter actually generates voice replies:
  - "vapi-native" (default): Vapi's own hosted model (GPT-4o-mini by
    default) generates every reply, using a system prompt built by
    VapiPromptAdapter from the same TwinContext as Text Chat. This is
    the only way to get real-time voice latency — a CPU-only local
    Ollama model's time-to-first-token is 10-100x too slow for a live
    conversation. Since Vapi generates the reply itself, we never see
    per-turn traffic; conversation memory is synced from the
    end-of-call-report webhook once the call ends.
  - "custom-llm": every voice reply is generated by this backend's own
    Ollama call (via OllamaPromptAdapter — the exact same adapter Text
    Chat uses), proxied through Vapi's custom-llm provider. Kept as a
    fully-working, configurable fallback for local-only inference; not
    the default because of the latency described above.

This class contains no personality logic in either mode — it only
decides which adapter to call and wires the result into Vapi's config
shape. All prompt content comes from app/adapters/.
"""

from __future__ import annotations

import time
import uuid
from typing import Dict, Iterator, List, Optional

from app.adapters import ollama_adapter, vapi_adapter
from app.config import (
    PUBLIC_BACKEND_URL,
    VAPI_CUSTOM_LLM_TIMEOUT_SECONDS,
    VAPI_LLM_PROVIDER,
    VAPI_NATIVE_MODEL,
    VAPI_NATIVE_MODEL_PROVIDER,
    VAPI_SECRET_HEADER,
    VAPI_SERVER_SECRET,
    VAPI_SILENCE_TIMEOUT_SECONDS,
    VAPI_TRANSCRIBER_LANGUAGE,
    VAPI_TRANSCRIBER_MODEL,
    VAPI_TRANSCRIBER_PROVIDER,
    VAPI_VOICE_ID,
    VAPI_VOICE_PROVIDER,
    VOICE_MAX_TOKENS,
    VOICE_TEMPERATURE,
    custom_llm_base_url,
    voice_enabled,
)
from app.services.ollama_client import OllamaClient
from app.services.twin_engine import DigitalTwinEngine, SessionNotFoundError

MAX_CALL_DURATION_SECONDS = 900  # 15 minutes — keeps a stray open call bounded


class VoiceChatService:
    def __init__(self, engine: DigitalTwinEngine | None = None):
        self.engine = engine or DigitalTwinEngine()
        self.client = OllamaClient()
        self.sessions: Dict[str, dict] = {}

    # ============================================================
    # Configuration status
    # ============================================================

    def is_configured(self) -> bool:
        return voice_enabled()

    # ============================================================
    # Call Lifecycle
    # ============================================================

    def start_session(self, profile_id: str) -> dict:
        session_id = str(uuid.uuid4())

        context = self.engine.build_twin_context(profile_id)
        history = self.engine.load_history(profile_id)
        opening_line = self.engine.build_opening_line(profile_id)

        self.sessions[session_id] = {
            "profile_id": profile_id,
            "context": context,
            "history": history,
            "status": "created",
            "started_at": time.time(),
            "call_id": None,
            # Pinned at session creation so a mid-flight config change
            # can't cause a session to be handled inconsistently between
            # the assistant config and the webhook/turn handlers.
            "llm_provider": VAPI_LLM_PROVIDER,
        }

        self.engine.touch_last_used(profile_id)

        # The greeting is spoken directly by Vapi as `firstMessage` — it
        # never passes through our custom-llm endpoint, and in
        # vapi-native mode we never see per-turn traffic at all — so we
        # record it into shared memory ourselves, right now, to keep
        # Text Chat and Voice Chat memory in sync from turn zero.
        self.sessions[session_id]["history"] = self.engine.append_message(
            profile_id, "assistant", opening_line, channel="voice"
        )

        assistant_config = self.build_assistant_config(session_id, opening_line)

        return {
            "session_id": session_id,
            "assistant": assistant_config,
        }

    def build_assistant_config(self, session_id: str, opening_line: str) -> dict:
        session = self.sessions[session_id]
        context = session["context"]
        provider = session["llm_provider"]

        config = {
            "name": "ReflectAI Twin",
            "firstMessage": opening_line,
            "firstMessageMode": "assistant-speaks-first",
            "voice": {
                "provider": VAPI_VOICE_PROVIDER,
                "voiceId": VAPI_VOICE_ID,
            },
            "transcriber": {
                "provider": VAPI_TRANSCRIBER_PROVIDER,
                "model": VAPI_TRANSCRIBER_MODEL,
                "language": VAPI_TRANSCRIBER_LANGUAGE,
            },
            "maxDurationSeconds": MAX_CALL_DURATION_SECONDS,
            "metadata": {
                "profile_id": session["profile_id"],
                "session_id": session_id,
            },
        }

        if PUBLIC_BACKEND_URL:
            config["server"] = {
                "url": f"{PUBLIC_BACKEND_URL}/api/voice/webhook",
                "headers": {VAPI_SECRET_HEADER: VAPI_SERVER_SECRET} if VAPI_SERVER_SECRET else {},
            }

        if provider == "vapi-native":
            # Vapi's own hosted model generates every reply — this is
            # the fast path. No custom-llm URL, no per-turn round trip
            # through our backend or the tunnel.
            config["model"] = {
                "provider": VAPI_NATIVE_MODEL_PROVIDER,
                "model": VAPI_NATIVE_MODEL,
                "messages": [{"role": "system", "content": vapi_adapter.build_prompt(context)}],
                "temperature": VOICE_TEMPERATURE,
            }
            # Vapi's own default silence timeout (~30s) is fine here —
            # GPT-4o-mini responds fast, no need to stretch it.
        else:
            # Every voice reply is generated by this backend's own
            # Ollama call, proxied through Vapi's custom-llm provider.
            # NOTE: `url` is used as an OpenAI client baseURL — Vapi
            # appends `/chat/completions` itself, so it must NOT be
            # included here.
            config["model"] = {
                "provider": "custom-llm",
                "url": custom_llm_base_url(session_id),
                "model": "reflectai-twin",
                "headers": {VAPI_SECRET_HEADER: VAPI_SERVER_SECRET} if VAPI_SERVER_SECRET else {},
                "timeoutSeconds": VAPI_CUSTOM_LLM_TIMEOUT_SECONDS,
                # Suppress Vapi's generic "You are an assistant." default —
                # our own backend always rebuilds the real system prompt,
                # this is purely cosmetic (keeps call transcripts clean).
                "messages": [],
            }
            # A CPU-only local model can take far longer than Vapi's
            # platform default silence timeout to produce a reply —
            # stretch it so a slow-but-successful turn survives.
            config["silenceTimeoutSeconds"] = VAPI_SILENCE_TIMEOUT_SECONDS

        return config

    def get_session(self, session_id: str) -> Optional[dict]:
        return self.sessions.get(session_id)

    def mark_call_started(self, session_id: str, call_id: Optional[str] = None) -> None:
        session = self.sessions.get(session_id)
        if session:
            session["status"] = "active"
            if call_id:
                session["call_id"] = call_id

    def end_session(self, session_id: str) -> dict:
        session = self.sessions.get(session_id)
        if session is None:
            raise SessionNotFoundError("Invalid voice session id")

        session["status"] = "ended"
        session["ended_at"] = time.time()
        self.engine.touch_last_used(session["profile_id"])

        return {
            "session_id": session_id,
            "status": "ended",
            "duration_seconds": round(session["ended_at"] - session["started_at"], 1),
        }

    # ============================================================
    # Custom-LLM turn handler (VAPI_LLM_PROVIDER=custom-llm only)
    # ============================================================
    # Vapi calls this once per user utterance with the running
    # conversation. We rebuild the prompt fresh from the engine every
    # time (so dynamic mood-adaptation applies to voice too), generate
    # the reply through the same Ollama model as Text Chat, and persist
    # both sides of the turn into the shared memory thread.

    def stream_turn(self, session_id: str, incoming_messages: List[dict]) -> Iterator[str]:
        session = self.sessions.get(session_id)
        if session is None:
            raise SessionNotFoundError("Invalid voice session id")

        profile_id = session["profile_id"]

        # Vapi may include its own system message(s) — we ignore those
        # and always drive the prompt from DigitalTwinEngine instead, so
        # voice never drifts from what Text Chat would say.
        turn_messages = [m for m in incoming_messages if m.get("role") in ("user", "assistant")]

        latest_user_message = None
        for m in reversed(turn_messages):
            if m.get("role") == "user":
                latest_user_message = m.get("content", "")
                break

        if latest_user_message and (not session["history"] or session["history"][-1].get("content") != latest_user_message):
            session["history"] = self.engine.append_message(
                profile_id, "user", latest_user_message, channel="voice"
            )

        dynamic_context = self.engine.build_dynamic_context(
            self.engine.get_recent_user_messages(session["history"])
        )

        system_messages = ollama_adapter.build_messages(session["context"])
        context_window = self.engine.build_context_window(
            system_messages,
            session["history"],
            dynamic_context=dynamic_context,
        )

        full_reply = []
        for token in self.client.stream_chat(
            context_window,
            temperature=VOICE_TEMPERATURE,
            max_tokens=VOICE_MAX_TOKENS,
        ):
            full_reply.append(token)
            yield token

        reply_text = "".join(full_reply).strip()
        if reply_text:
            session["history"] = self.engine.append_message(
                profile_id, "assistant", reply_text, channel="voice"
            )

    # ============================================================
    # Webhook events
    # ============================================================

    def handle_webhook_event(self, payload: dict) -> dict:
        message = payload.get("message", payload)
        event_type = message.get("type")
        call = message.get("call", {})
        # `assistant` (and its `metadata`) is a sibling of `call` at the
        # top level of the message, not nested inside it.
        metadata = (message.get("assistant") or {}).get("metadata") or call.get("metadata") or {}
        session_id = metadata.get("session_id")

        session = self.sessions.get(session_id) if session_id else None

        if event_type == "status-update" and session:
            status = message.get("status")
            if status == "in-progress":
                self.mark_call_started(session_id, call.get("id"))
            elif status in ("ended", "forwarding"):
                session["status"] = "ended"

        elif event_type == "end-of-call-report" and session:
            session["status"] = "ended"
            session["ended_reason"] = message.get("endedReason")
            self.engine.touch_last_used(session["profile_id"])

            # In vapi-native mode we never see per-turn traffic — the
            # only way we learn what was actually said is this report.
            # custom-llm mode already synced every turn live in
            # stream_turn(), so re-syncing here would duplicate it.
            if session.get("llm_provider") == "vapi-native":
                self._sync_transcript_from_report(session, message)

        return {"received": True, "type": event_type}

    def _sync_transcript_from_report(self, session: dict, report_message: dict) -> None:
        artifact = report_message.get("artifact", {})
        formatted = artifact.get("messagesOpenAIFormatted") or report_message.get("messagesOpenAIFormatted") or []
        turns = [m for m in formatted if m.get("role") in ("user", "assistant")]

        # The first turn is always the firstMessage greeting, which we
        # already appended to shared memory the instant the call started.
        new_turns = turns[1:]

        profile_id = session["profile_id"]
        for turn in new_turns:
            content = (turn.get("content") or "").strip()
            if content:
                session["history"] = self.engine.append_message(
                    profile_id, turn["role"], content, channel="voice"
                )
